server:
  session-timeout: 1800
#    tomcat:
#        max-threads: 1000
#        min-spare-threads: 30
  port: 8080
#   port: 8080
#    uri-encoding: utf-8
security:
  basic:
    enabled: false
spring:
  profiles:
    active: dev
  thymeleaf:
    mode: LEGACYHTML5
    cache: false
    content-type: text/html
    prefix: classpath:/static/
    encoding: UTF-8
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss
  http:
    multipart:
      max-file-size: 200Mb
      max-request-size: 200Mb
      enabled: true
#      location:
      resolve-lazily: true
  devtools:
    restart:
      enabled: true    
mybatis: 
  configuration:
    map-underscore-to-camel-case: true
  mapper-locations: mybatis/**/*Mapper.xml
  typeAliasesPackage: com.frode.**.domain
#配置缓存和session存储方式，默认ehcache,可选redis
cacheType: ehcache
